name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  compile-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Display compilation errors
      continue-on-error: true
      run: mvn -B compile

    - name: Test if compilation succeeded
      id: check-compilation
      run: |
        if mvn -B clean compile -DskipTests; then
          echo "compilation=success" >> $GITHUB_OUTPUT
        else
          echo "compilation=failure" >> $GITHUB_OUTPUT
        fi

  test-only:
    runs-on: ubuntu-latest
    needs: compile-check
    # Always run, even if compilation fails
    if: always()
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Compile tests only
      continue-on-error: true
      run: mvn -B test-compile -Dmaven.main.skip=true
      
    - name: Check if tests compile
      id: test-compilation
      run: |
        if mvn -B test-compile -Dmaven.main.skip=true; then
          echo "tests_compile=true" >> $GITHUB_OUTPUT
        else
          echo "tests_compile=false" >> $GITHUB_OUTPUT
        fi

    - name: Report Status
      run: |
        if [[ "${{ steps.test-compilation.outputs.tests_compile }}" == "true" ]]; then
          echo "✅ Test compilation successful! Main code issues need to be fixed (see Issue #9)"
        else
          echo "❌ Tests also have compilation issues that need to be fixed"
        fi
